# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgRdgyDAikewXv8CAdOd6EKzL_eimSHd
"""

!pip install -r requirements.txt

import gradio as gr
import joblib
import pandas as pd

# Load the trained model
model = joblib.load("model.pkl")

# Define the prediction function
def predict_price(area, bedrooms, bathrooms):
    input_data = pd.DataFrame({
        "area": [area],
        "bedrooms": [bedrooms],
        "bathrooms": [bathrooms]
    })
    prediction = model.predict(input_data)
    return round(prediction[0], 2)

# Create the Gradio interface
interface = gr.Interface(
    fn=predict_price,
    inputs=[
        gr.Number(label="Area (sq ft)"),
        gr.Number(label="Bedrooms"),
        gr.Number(label="Bathrooms")
    ],
    outputs=gr.Number(label="Predicted Price"),
    title="Housing Price Predictor",
    description="Enter house details to get an estimated price based on a trained linear regression model."
)

# Launch the app
if __name__ == "__main__":
    interface.launch()